### ISSUE TITLE
Fail to run the example in readme

### ISSUE THREAD

**Issue by jakezhu9** [shrink/actions-docker-extract#26]
https://github.com/shrink/actions-docker-extract/blob/e8af259fb1dee032812f761b778eb6858193ef0e/README.md?plain=1#L39-L58

I try to run this example, but i got a warning in docker/build-push-action:
```
Warning: Unexpected input(s) 'repository', valid inputs are ['add-hosts', 'allow', 'annotations', 'attests', 'build-args', 'build-contexts', 'builder', 'cache-from', 'cache-to', 'cgroup-parent', 'context', 'file', 'labels', 'load', 'network', 'no-cache', 'no-cache-filters', 'outputs', 'platforms', 'provenance', 'pull', 'push', 'sbom', 'secrets', 'secret-envs', 'secret-files', 'shm-size', 'ssh', 'tags', 'target', 'ulimit', 'github-token']
```

and error in shrink/actions-docker-extract:
```
Unable to find image 'my-example-image:latest' locally
Error response from daemon: pull access denied for frontend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
must specify at least one container source
Error: The process '/bin/bash' failed with exit code 1
```

I think it should be: 
```
         uses: docker/build-push-action@v5 
         with: 
           tags: my-example-image:latest 
```

**Comment by shrink** [comment]
> I try to run this example, but i got a warning in docker/build-push-action:

Sorry about that! I made a mistake when upgrading the examples to the latest version of `docker/build-push-action` which is not backwards compatible with the previous version ([v1](https://github.com/docker/build-push-action/tree/92e71463491f2d026a477188b8ad3a0fdd9d672c)): 

> `repository` Required Docker repository to tag the image with.
> `tags` Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags.

If you change the example to...

```diff
       - name: Build Docker Image 
         uses: docker/build-push-action@v5 
         with: 
-          repository: my-example-image 
-          tags: latest 
+          tags: my-example-image/latest
+          push: true
```

That should work. I'll update the README.

> ...and error in shrink/actions-docker-extract:...

That error is because the previous step failed, once the previous step is working this should start working. If you encounter any further issues, let me know!

**Comment by shrink** [comment]
@jakezhu9 the README example is fixed now, and I've added tests to confirm it works. Thank you for flagging!
